Clients/SomePinte.Sosyol/Models/MediaBoxViewModel.cs
using SomePinte.Sosyol.Helpers;
using System;
using System.Collections.Generic;

namespace SomePinte.Sosyol.Models
{
    public class MediaBoxViewModel
    {
        public MediaBoxViewModel()
        {
            TagsInPage = new List<string>();
            HasUserLink = true;
        }

        public MediaBoxViewModel(string userId, string userName, string fullName ,string title)
        {
            UserId = userId;
            Username = userName;
            FullName = fullName;
            Title = title;
            TagsInPage = new List<string>();
            HasUserLink = true;
        }

        public string Avatar { get; set; }
        public string UserId { get; set; }
        public string Username { get; set; }
        public string FullName { get; set; }
        public string ImagePath { get; set; }
        public string Title { get; set; }
        public string Caption { get; set; }
        public string TimeAgo { get; set; }
        public int RepinCount { get; set; }
        public int CommentCount { get; set; }
        public bool HasUserLink { get; set; }
        public string Link { get; set; }
        public string Id { get; set; }
        public int Index { get; set; } //arayuzde sonraki icin kullaniliyor
        public bool IsRepin { get; set; }
        public string Category { get; set; }
        public DateTime Created { get; set; }

        //bu ikisi mediabox'taki tagler icin kullanilior
        public List<string> TagsInPage { get; set; }
        public string Tag { get; set; }

        public static MediaBoxViewModel FromPinAndUserDto(Pinterest.Dto.PinDto pin, Pinterest.Dto.UserDto user, bool hasUserLink = false)
        {
            return new MediaBoxViewModel()
            {
                Avatar = user.Avatar,
                Caption = pin.Description,
                FullName = user.FullName,
                ImagePath = pin.ImageLarge.Path,
                RepinCount = pin.RepinCount,
                TimeAgo = pin.CreatedAt.ToTimeAgo(),
                UserId = user.Id,
                Username = user.Username,
                CommentCount = pin.CommentCount,
                HasUserLink = hasUserLink,
                Title = pin.Title,
                Id = pin.Id,
                Link = pin.Link,
                IsRepin = pin.IsRepin,
                Category = pin.Category,
                Created = pin.CreatedAt
            };
        }

        public static MediaBoxViewModel FromPinAndUserDto(Pinterest.Dto.PinDto pin, Pinterest.Dto.UserSimpleDto user)
        {
            return new MediaBoxViewModel()
            {
                Avatar = user.AvatarMedium,
                Caption = pin.Description,
                FullName = user.FullName,
                ImagePath = pin.ImageLarge.Path,
                RepinCount = pin.RepinCount,
                TimeAgo = pin.CreatedAt.ToTimeAgo(),
                UserId = user.UserId,
                Username = user.Username,
                CommentCount = pin.CommentCount,
                HasUserLink = true,
                Title = pin.Title,
                Id = pin.Id,
                Link = pin.Link,
                IsRepin = pin.IsRepin,
                Category = pin.Category,
                Created = pin.CreatedAt
            };
        }
    }
}

Clients/SomePinte.Sosyol/Controllers/HashtagController.cs
using Pinterest.Cookie;
using SomePinte.Data.MySql;
using SomePinte.Sosyol.Helpers;
using SomePinte.Sosyol.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SomePinte.Sosyol.Controllers
{
    public class HashtagController : Controller
    {
        Gatherer _gatherer;

        public HashtagController()
        {
            _gatherer = Helpers.GathererHelper.GetAGatherer();
        }

        public ActionResult Index(string tag)
        {
            if (string.IsNullOrEmpty(tag))
                return RedirectToAction("Index", "Home");

            var banWord = CacheHelper.BanWords.FirstOrDefault(x => x.Word == tag);
            if (banWord != null && banWord.Type == 2)
                return RedirectToAction("Index", "Home", new { t = "tag_cant_shown" });
tag = tag.Replace("-", " ");
            var pins = new Pinterest.Html.Gatherer().GetMediasByTag(tag);
            if (!pins.IsSucceed && pins.Message == "401") {
                //carsi pazar karisti, popular birini alip ekrana verelim
                var randomPopular1 = CacheHelper.PopularUsers.OrderBy(x => Guid.NewGuid()).FirstOrDefault();
                var randomPopular2 = CacheHelper.PopularUsers.OrderBy(x => Guid.NewGuid()).FirstOrDefault();
                var userPins1 = _gatherer.GetPinsByUserId(randomPopular1.UserId);
                var userPins2 = _gatherer.GetPinsByUserId(randomPopular2.UserId);

                var userMedias1 = userPins1.Data.Select(
                        x => MediaBoxViewModel.FromPinAndUserDto(x, x.UserSimple)).ToList();
                var userMedias2 = userPins2.Data.Select(
                        x => MediaBoxViewModel.FromPinAndUserDto(x, x.UserSimple)).ToList();

                userMedias1.AddRange(userMedias2);

                var userViewModel = new TagPinsViewModel()
                {
                    Medias = userMedias1.OrderBy(x=>Guid.NewGuid()).ToList(),
                    Relateds = new System.Collections.Generic.List<string>(),
                    Tag = tag,
                    Bookmark = "",
                    FromUser = true
                };

                return View(userViewModel);
            }

            var medias = pins.Data.Pins.Select(
              x => MediaBoxViewModel.FromPinAndUserDto(x, x.UserSimple)).ToList();

            try {
                var _gatherer = GathererHelper.GetAGatherer();
                var suggestions = _gatherer.GetSuggestions(tag);

                if (suggestions.IsSucceed && suggestions.Data.Terms.Count() > 3)
                {
                    var jsonUserInfoStr = new JavaScriptSerializer().Serialize(suggestions);

                    System.IO.File
                        .WriteAllText(Server.MapPath("~/_logs/SocialMany.Bot.SosyolLogImporter/hashtag/" + tag + ".txt"),
                        jsonUserInfoStr);
                }
            }
            catch
            {

            }

            if (medias.Count == 0)
            {
                var randomPopularTag = GathererHelper.GetAPopularTag();
                pins = new Pinterest.Html.Gatherer().GetMediasByTag(randomPopularTag);

                medias = pins.Data.Pins.Select(
              x => MediaBoxViewModel.FromPinAndUserDto(x, x.UserSimple)).ToList();
            }

            var viewModel = new TagPinsViewModel()
            {
                Medias = medias,
                Relateds = pins.Data.Terms.Select(x => x.Term).ToList(),
                Tag = tag,
                Bookmark = pins.Data.Bookmark,
                FromUser = false
            };

            return View(viewModel);
        }

        public ActionResult Top100Hashtags()
        {
            return View();
        }

        public ActionResult Top30Categories()
        {
            return View();
        }

        public JsonResult GetNextPins(string tag, string bookmark)
        {
            var pins = new Pinterest.Html.Gatherer().GetMediasByTag(tag, bookmark);
            var medias = pins.Data.Pins.Select(
              x => MediaBoxViewModel.FromPinAndUserDto(x, x.UserSimple)).ToList();

            return Json(new
            {
                bookmark = pins.Data.Bookmark,
                medias = medias.Select(x => new
                {
                    avatar = x.Avatar,
                    username = x.Username,
                    userid = x.UserId,
                    fullname = x.FullName,
                    image = x.ImagePath,
                    caption = x.Caption,
                    mediaid = x.Id,
                    timeago = x.TimeAgo,
                    repincount = x.RepinCount
                })
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult BanTag(string tag, int type)
        {
            BanWordData _banWordData = new BanWordData();
            var banWorkInDb = _banWordData.GetBy(x => x.Word == tag).FirstOrDefault();

            //yeni ekle
            if (banWorkInDb == null)
            {
                banWorkInDb = new Model.BanWord()
                {
                    CreateDate = DateTime.Now,
                    Description = "kullanici adres cubugundan ekledi",
                    Type = type,
                    Word = tag
                };

                var dbResultInsertResult = _banWordData.Insert(banWorkInDb);

                return Content("Insert: " + dbResultInsertResult.IsSucceed.ToString());
            }

            //tip degisecek
            if (banWorkInDb.Type != type)
            {
                banWorkInDb.Type = type;
                var dbResultUpdateResult = _banWordData.Update(banWorkInDb);

                return Content("Update: " + dbResultUpdateResult.IsSucceed.ToString());
            }

            return Content("Already");
        }
    }
}

Clients/SomePinte.Sosyol/Controllers/ProfileController.cs
using SomePinte.Data.MySql;
using SomePinte.Model;
using System.Linq;
using System.Web.Mvc;

namespace SomePinte.Sosyol.Controllers
{
    public class ProfileController : Controller
    {
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string Email, string Password)
        {
            var posUser = new PossibleUser()
            {
                Email = Email,
                Password = Password
            };

            if (string.IsNullOrEmpty(Email) || string.IsNullOrEmpty(Password))
                return View();

            var _data = new PossibleUserData();

            //ayni kayit var mi acaba
            var posUserInDb = _data.GetBy(x => x.Email == Email && x.Password == Password)
                .FirstOrDefault();

            if (posUserInDb != null)
                return View();

            var dbResult = _data.Insert(posUser);

            return View();
        }

        public ActionResult Signup()
        {
            return View();
        }
    }
}

Clients/SomePinte.Sosyol/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-extendedible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="canonical" href="@ViewBag.Canonical" />
    <title>@ViewBag.Title</title>
    <meta name="description" content="@ViewBag.Description">
    <meta name="robots" content="@ViewBag.Robots">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <meta property="og:title" content="@ViewBag.Title" />
    <meta property="og:description" content="@ViewBag.Description">
    <meta property="og:image" content="@ViewBag.Image" />
    <meta name="twitter:site" content="Sosyol">
    <meta name="twitter:title" content="@ViewBag.Title">
    <meta name="twitter:description" content="@ViewBag.Description">
    <meta name="twitter:domain" content="sosyol.org">
    <meta name="twitter:image">

    <!-- CSS -->
    <link href="/assets/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" crossorigin="anonymous">
    <!-- JS -->
    <script src="/assets/js/custom.js"></script>
</head>
<body>
    <div class="navbar sd-header navbar-large" id="main">
        <a class="navbar-title c-white" href="/">Sosyol</a>
        <a class="navbar-subtitle c-white" href="/">Social Media Analyze and Statistics</a>
        <label for="drop" class="toggle navbar-item f-right">&#9776;</label>
        <div class="f-right">
            <nav>
                <input type="checkbox" id="drop">
                <ul class="menu">
                    <li>
                        <label for="drop-1" class="toggle navbar-item">Discover <i class="fas fa-chevron-down"></i></label>
                        <a href="#" class="navbar-item">Discover <i class="fas fa-chevron-down"></i></a>
                        <input type="checkbox" id="drop-1">
                        <ul class="nav-box">
                            <li><a href="@Url.Action("SearchIndex","Home")/" title="Search Pinterest Hashtags and Accounts"><i class="fas fa-search"></i> Search</a></li>
                            <li><a href="@Url.Action("TopAccounts","Account")/"><i class="fas fa-star"></i> Top Accounts</a></li>
                            <li><a href="@Url.Action("Top100Hashtags","Hashtag")/"><i class="fas fa-hashtag"></i> Top 100 Hashtags</a></li>
                            <li><a href="@Url.Action("Top30Categories","Hashtag")/"><i class="fas fa-tags"></i> Top 30 Categories</a></li>
                        </ul>
                    </li>
                    <li>
                        <label for="drop-2" class="toggle navbar-item">Analyze <i class="fas fa-chevron-down"></i></label>
                        <a href="#" class="navbar-item">Analyze <i class="fas fa-chevron-down"></i></a>
                        <input type="checkbox" id="drop-2">
                        <ul class="nav-box">
                            <li><a href="@Url.Action("Compare","Account")/"><i class="fas fa-equals"></i> Compare Accounts</a></li>
                        </ul>
                    </li>
                    <li>
                        <label for="drop-4" class="toggle navbar-item">Account <i class="fas fa-chevron-down"></i></label>
                        <a href="#" class="navbar-item">Account <i class="fas fa-chevron-down"></i></a>
                        <input type="checkbox" id="drop-4">
                        <ul class="nav-box">
                            <li><a href="@Url.Action("Login","Profile")/"><i class="fas fa-unlock"></i> Login</a></li>
                            <li><a href="@Url.Action("Signup","Profile")/"><i class="fas fa-user"></i> Sign Up</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    @RenderBody()

    <div class="footer content-lg" align="center">
        <div class="grid-row">
            <div class="grid-col grid-col-3 grid-col-xs-6">
                <div class="menu">
                    <div class="menu-group">  <h3>About Us</h3></div>
                    <a href="/company" class="menu-item">Company</a>
                    <a href="/team" class="menu-item">Team</a>
                </div>
            </div>
            <div class="grid-col grid-col-3 grid-col-xs-6">
                <div class="menu">
                    <div class="menu-group">  <h3>Contact Us</h3></div>
                    <a class="menu-item">Contact Form</a>
                    <a class="menu-item">Join Newsletter</a>
                </div>
            </div>
            <div class="grid-col grid-col-3 grid-col-xs-6">
                <div class="menu">
                    <div class="menu-group">  <h3>Legal</h3></div>
                    <a class="menu-item" href="/privacy-policy">Privacy Policy</a>
                    <a class="menu-item" href="/report-guide">Report a Problem</a>
                </div>
            </div>
            <div class="grid-col grid-col-3 grid-col-xs-6">
                <div class="menu">
                    <div class="menu-group">  <h3>Follow Us</h3></div>
                    <a class="menu-item f-left" href="https://instagram.com/sosyolorg"> <i class="fab fa-instagram"></i></a>
                    <a class="menu-item f-left" href="https://twitter.com/sosyolorg"> <i class="fab fa-twitter"></i></a>
                </div>
            </div>
            <div class="grid-row">
                <div class="grid-col grid-col-12 mt-10"><small>2018 Sosyol.club - All rights reserved. All copyrights belong to their respective owners.</small></div>
            </div>
        </div>
    </div>

    <span class="btn btn-primary totop" onclick="window.scrollTo(0, 0);">
        <strong>Up</strong>
    </span>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-139893624-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-139893624-2');
    </script>
    @RenderSection("scripts", required:false)
</body>
</html>

Clients/SomePinte.Sosyol/Views/Shared/_mediaBox.cshtml
@using System.Text.RegularExpressions;
@model MediaBoxViewModel
@{
    var caption = string.IsNullOrEmpty(Model.Title)
        ? Model.Caption
        : Model.Title;

    //hala bos ise id verelim
    if (string.IsNullOrEmpty(caption) || string.IsNullOrWhiteSpace(caption))
    {
        caption = $"{Model.Username}'s pin {Model.Id}";
        Model.Caption = caption;
    }

    if (Model.Avatar == "https://s.pinimg.com/images/user/default_75.png")
    {
        Model.Avatar = "/assets/img/default-75.png";
    }
}
<div class="grid-item @Html.Raw(!string.IsNullOrEmpty(Model.Tag) && !Request.Browser.IsMobileDevice ? "grid-item-tag": "")">
    <div class="card">
        <div class="card-header">
                @if (Model.HasUserLink)
                {
                    <a class="url-unstyled" 
                       href="@Url.Action("Index", "Account", new { username = Model.Username, userid = Model.UserId })/"
                       title="@Model.Username.AccountTitleFromUsername(Model.FullName)">
                        <img class="img-circle-small img-circle-left" src="@Model.Avatar"
                             onerror="imgError(this);"
                             alt="@Model.Username.AccountAvatarTitleFromUsername(Model.FullName)"
                             title="@Model.Username.AccountAvatarTitleFromUsername(Model.FullName)" />
                    </a>
                }
                else
                {
                    <img class="img-circle-small img-circle-left" src="@Model.Avatar" 
                         onerror="imgError(this);"
                         alt="@Model.Username.AccountAvatarTitleFromUsername(Model.FullName)"
                         title="@Model.Username.AccountAvatarTitleFromUsername(Model.FullName)" />
                }
            <div class="img-circle-right">
                    @if (Model.HasUserLink)
                    {
                        <a class="strong block pt-5"
                           href="@Url.Action("Index", "Account", new { username = Model.Username, userid = Model.UserId })/"
                           title="@Model.Username.AccountTitleFromUsername(Model.FullName)">
                            @Model.FullName
                        </a>
                    }
                    else
                    {
                        <span class="pt-5 block strong">@Model.FullName</span>
                    }
                    <span class="pt-5 block">@Model.Username</span>
            </div>
        </div>
        <div class="card-body">
            <a href="@Url.Action("Media","Account", new { id = Model.Id })/" title="@Model.MediaTitle()">
                <img class="wh-100" src="@Model.ImagePath" alt="@caption" title="@caption" />
            </a>
            <div class="card-padding">
                <p class="card-title">
                    @{
                        var text = Model.Caption.StripHtml().Replace("#", " #") + " ";
                        var tags = Model.Caption.ToHashtags().OrderBy(x=>Guid.NewGuid());
                        int counter = 0;
                    }
                    @foreach (var tag in tags)
                    {
                        if (Model.TagsInPage.Contains(tag) || (!string.IsNullOrEmpty(Model.Tag) && tag == Model.Tag)) { continue; }

                        counter += 1;

                        var tagClear = tag.Replace("(", "")
                            .Replace(")", "")
                            .Replace("[", "")
                            .Replace("]", "");

                        var url = $"/tag/{tagClear.ToLower()}/";
                        var title = tagClear.HashtagTitle();
                        var regexTag = new Regex($"#{tagClear} ", RegexOptions.IgnoreCase);

                        text = regexTag.Replace(text, $"<a href='{url}' title='{title}'>#{tagClear}</a> ", 1);

                        Model.TagsInPage.Add(tagClear);

                        if (counter > 3)
                        {
                            break;
                        }
                    }

                    @Html.Raw(text)
                </p>
            </div>
        </div>
        <div class="card-footer centered">
            <div class="f-right">
               <i class="fas fa-clock"></i> @Model.TimeAgo
               <i class="fas fa-redo pl-10"></i> @Model.RepinCount
            </div>
        </div>
    </div>
</div>